baseurl = 'https://michimauch.github.io/'
languageCode = 'en-us'
title = 'Unser Womolog'
author = 'Michi'
theme = 'vinyl-records-collection-theme'

[taxonomies]
  art_des_platzes = 'art_des_platzes'
  ausstattung = 'ausstattung'
  genres = 'genres'
  label = 'label'
  year = 'year'
  format = 'format'