backend:
  name: git-gateway
  branch: main

media_folder: "static/img" # Pfad, wo Medien gespeichert werden
public_folder: "/img" # Pfad, wie er im CMS angezeigt wird

collections:
  - name: "plaetze" # Name der Sammlung
    label: "Plätze" # Label, das im CMS angezeigt wird
    folder: "content/plaetze/" # Verzeichnis im Repository
    summary: "{{title}} - {{date | date('DD.MM.YYYY')}}"
    create: true # Erlaubt das Erstellen neuer Einträge
    fields: # Felder für jeden Eintrag
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Entwurf", name: "draft", widget: "boolean"}
      - {label: "Typ", name: "type", widget: "hidden", default: "default"}
      - {label: "Beschreibung", name: "description", widget: "text"}
      - {label: "Anzahl Nächte", name: "anzahl_naechte", widget: "number"}
      - {label: "Aufenthalt von bis", name: "aufenthalt_von_bis", widget: "string"}
      - {label: "Preis", name: "preis", widget: "string"}
      - label: "Art des Platzes"
        name: "art_des_platzes"
        widget: "select"
        options:
          - {label: "Stellplatz", value: "Stellplatz"}
          - {label: "Campingplatz", value: "Campingplatz"}
      - label: "Koordinaten"
        name: "coordinates"
        widget: "object"
        fields:
          - label: "Breitengrad"
            name: "latitude"
            widget: "number"
            step: 0.00001
            value_type: "float"
          - label: "Längengrad"
            name: "longitude"
            widget: "number"
            step: 0.00001
            value_type: "float"
      - label: "Marker Icon"
        name: "marker_icon"
        widget: "select"
        options:
          - {label: "Stellplatz", value: "/stellplatz.png"}
          - {label: "Campingplatz", value: "/campingplatz.png"}
          - {label: "Parkplatz", value: "/parkplatz.png"}
      - label: "Ausstattung"
        name: "ausstattung"
        widget: "list"
        fields:
          - label: "Ausstattung"
            name: "ausstattung"
            widget: "select"
            options:
              - {label: "Entsorgung", value: "Entsorgung"}
              - {label: "Versorgung", value: "Versorgung"}
              - {label: "WC/Dusche", value: "WC/Dusche"}
              - {label: "WLAN", value: "WLAN"}
              - {label: "Laden auf Platz", value: "Laden auf Platz"}
              - {label: "Laden in Laufnähe", value: "Laden in Laufnähe"}
              - {label: "Restaurant auf Platz", value: "Restaurant auf Platz"}
      - label: "Aktivitäten"
        name: "aktivitaeten"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
          - label: "Icon"
            name: "icon"
            widget: "select"
            options:
              - {label: "Wandern", value: "fa-solid fa-person-hiking"}
              - {label: "Spazieren", value: "fa-solid fa-person-walking"}
              - {label: "Mountainbike", value: "fa-solid fa-bicycle"}
              - {label: "Schwimmen", value: "fa-solid fa-person-swimming"}
      - {label: "Titelbild", name: "cover", widget: "image"}
      - label: "Bilder"
        name: "pictures"
        widget: "list"
        field: {label: "Bild", name: "image", widget: "image"}